name: CI - Create Release And Publish Package

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    if: contains(github.head_ref, 'release-') && contains(github.base_ref, 'main') && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract branch tag
        id: tag
        run: |
          BRANCH=${{ github.head_ref }}
          TAG="${BRANCH//release-/""}"
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  publish-package:
    needs:
      - TAG
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      TAG: ${{ needs.TAG.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@bduaart'
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/bduaart/monorepo-js
          yarn install
          lerna version ${{ env.TAG }} --conventional-commits --create-release github --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  release:
#    needs:
#      - TAG
#    runs-on: ubuntu-latest
#    env:
#      TAG: ${{ needs.TAG.outputs.tag }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Push Tag
#        uses: mathieudutour/github-tag-action@v6.1
#        with:
#          github_token: ${{ secrets.NODE_PACKAGE_TOKEN }}
#
#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          name: v${{ env.TAG }}
#          tag_name: v${{ env.TAG }}
#          generate_release_notes: true
#          token: ${{ secrets.NODE_PACKAGE_TOKEN }}